### ISSUE TITLE
Design: "empty" nodes

### ISSUE THREAD

**Issue by rphmeier** [thrumdev/nomt#12]
The specification in #7 describes an "empty" node, which is not actually a node at all but a special node hash which indicates that there are no values stored in the trie beyond that point.

Quoting from the [JMT paper](https://developers.diem.com/papers/jellyfish-merkle-tree/2021-01-14.pdf)

> Some works create an identical default digest only for the empty nodes on the same height ℎ ...
> In this paper, we choose a single default digest 𝐷_𝑑𝑒𝑓𝑎𝑢𝑙𝑡 to represent empty subtrees at any level without ambiguity, especially in our design.

This is essentially the function of the zero hash in the specification. I believe that this approach is also suitable for our case, but it should be noted that ~~this is not a node but rather a placeholder referenced by internal nodes.~~

**Comment by gabriele-0201** [comment]
The reason I see 'Terminator'/'empty' nodes as a special kind of node is because I believe that all nodes are backed by pages, and the key path is the 'rule' that guides movement between nodes. A page will always be filled by nodes, although some may be unreachable. To distinguish between these two worlds, there is the special node, the 'terminator'. This concept makes sense to me when assuming that each internal node has two children, which can be internal, leaf, and in special cases, terminator nodes.

Describing the terminator as a 'placeholder referenced by internal nodes' undermines the assumption of each internal node having two children.

These are just theoretical ideas. I am leaning to maintain the concept of the Terminator Node Hash but renaming it to Terminator Hash and using it as a placeholder to indicate an empty sub-tree is also ok! I don't have strong preferences

**Comment by rphmeier** [comment]
> The reason I see 'Terminator'/'empty' nodes as a special kind of node is because I believe that all nodes are backed by pages

This doesn't hold water. The schema and the storage are two separate things.

But re: #16 the terminator is a node in this framing

**Comment by rphmeier** [comment]
![image](https://github.com/thrumdev/nomt/assets/10121380/3742ec9f-0ec6-4405-8349-391ad9da5462)

^ referring to the JMT paper & reposting from DM - what I mean above is that the terminator node (and variable-depth leaf nodes) are both tools for a **tractable representation** of the trie and are almost completely unrelated to the pages itself. Variable-depth leaf nodes and terminator nodes are, conceptually, extensions of the basic SMT to allow it to be represented compactly.
